import json
import os
from typing import Dict, List

import numpy as np

from program_loader import ProgramLoader


def _clip_int4(x: int) -> int:
    if x > 7:
        return 7
    if x < -8:
        return -8
    return int(x)


def _leaky_relu_shift_int4(x: int, alpha_shift: int = 2) -> int:
    if x < 0:
        return int(np.int8(x) >> alpha_shift)
    return x


def _pack_int4_fetch_bytes(vals: np.ndarray) -> List[int]:
    out = []
    flat = vals.astype(np.int8).tolist()
    for i in range(0, len(flat), 4):
        chunk = flat[i:i + 4]
        while len(chunk) < 4:
            chunk.append(0)
        lo = (chunk[0] & 0xF) | ((chunk[1] & 0xF) << 4)
        hi = (chunk[2] & 0xF) | ((chunk[3] & 0xF) << 4)
        out.extend([lo, hi])
    return out


def _fc_block_reference(
    fc1_w: np.ndarray,
    fc2_w: np.ndarray,
    x: np.ndarray,
    fc1_relu: bool,
    fc2_relu: bool,
    alpha_shift: int = 2,
) -> Dict[str, List[int]]:
    fc1_acc = np.matmul(fc1_w.astype(np.int32), x.astype(np.int32))
    fc1_q = np.array([_clip_int4(int(v)) for v in fc1_acc], dtype=np.int8)
    if fc1_relu:
        fc1_q = np.array([_leaky_relu_shift_int4(int(v), alpha_shift) for v in fc1_q], dtype=np.int8)

    fc2_acc = np.matmul(fc2_w.astype(np.int32), fc1_q.astype(np.int32))
    fc2_q = np.array([_clip_int4(int(v)) for v in fc2_acc], dtype=np.int8)
    if fc2_relu:
        fc2_q = np.array([_leaky_relu_shift_int4(int(v), alpha_shift) for v in fc2_q], dtype=np.int8)

    return {
        "fc1_int32": fc1_acc.tolist(),
        "fc1_int4": fc1_q.tolist(),
        "fc2_int32": fc2_acc.tolist(),
        "fc2_int4": fc2_q.tolist(),
        "fc2_fetch_bytes": _pack_int4_fetch_bytes(fc2_q),
    }


def _write_program_mem(path: str, program: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for i in range(0, len(program), 2):
            word = int.from_bytes(program[i:i + 2], byteorder="little", signed=False)
            f.write(f"{word:04x}\n")


def _count_ops(program: bytes) -> Dict[str, int]:
    counts = {"bstore_count": 0, "load_count": 0, "run_count": 0, "fetch_count": 0, "halt_count": 0}
    words = [int.from_bytes(program[i:i + 2], "little") for i in range(0, len(program), 2)]
    i = 0
    while i < len(words):
        op = words[i] & 0x7
        if op == 0b110:
            counts["bstore_count"] += 1
            burst_n = words[i + 1]
            i += 2 + burst_n
        elif op == 0b011:
            counts["load_count"] += 1
            i += 1
        elif op == 0b010:
            counts["run_count"] += 1
            i += 1
        elif op == 0b001:
            counts["fetch_count"] += 1
            i += 1
        elif op == 0b100:
            counts["halt_count"] += 1
            i += 1
        elif op == 0b000:
            i += 3
        else:
            i += 1
    return counts


def _build_case(loader: ProgramLoader, name: str, fc1_w: np.ndarray, fc2_w: np.ndarray, x: np.ndarray) -> Dict:
    fused = loader.build_full_inference_program_compressed_fused(
        fc1_weights_int4=fc1_w,
        fc2_weights_int4=fc2_w,
        input_activations_int4=x,
        array_size=16,
        fc1_apply_relu=True,
        fc2_apply_relu=False,
        apply_quant=True,
    )
    ref = _fc_block_reference(fc1_w, fc2_w, x, fc1_relu=True, fc2_relu=False)
    op_counts = _count_ops(fused["program"])
    words = len(fused["program"]) // 2

    mem_path = os.path.join("build", "test_vectors", f"{name}_fused_program.mem")
    _write_program_mem(mem_path, fused["program"])

    return {
        "name": name,
        "program_mem": mem_path,
        "program_words": words,
        "expected_outputs": ref["fc2_int4"],
        "expected_fetch_bytes": ref["fc2_fetch_bytes"],
        "expected_fc1_int4": ref["fc1_int4"],
        "expected_fc1_int32": ref["fc1_int32"],
        "expected_fc2_int32": ref["fc2_int32"],
        **op_counts,
    }


def _write_svh(summary: Dict, path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    case1 = summary["cases"][0]
    case2 = summary["cases"][1]
    case1_mem = case1["program_mem"].replace("\\", "/")
    case2_mem = case2["program_mem"].replace("\\", "/")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_fused_rtl_test_vectors.py\n")
        f.write(f'`define CASE1_MEM "{case1_mem}"\n')
        f.write(f'`define CASE2_MEM "{case2_mem}"\n')
        f.write(f'`define CASE1_WORDS {case1["program_words"]}\n')
        f.write(f'`define CASE2_WORDS {case2["program_words"]}\n')
        f.write(f'`define CASE1_FETCH_N {len(case1["expected_fetch_bytes"])}\n')
        f.write(f'`define CASE2_FETCH_N {len(case2["expected_fetch_bytes"])}\n')
        for idx, val in enumerate(case1["expected_fetch_bytes"]):
            f.write(f"`define CASE1_EXP_BYTE_{idx} 8'h{val:02x}\n")
        for idx, val in enumerate(case2["expected_fetch_bytes"]):
            f.write(f"`define CASE2_EXP_BYTE_{idx} 8'h{val:02x}\n")


def generate_vectors(output_json: str = os.path.join("build", "test_vectors", "fused_expected.json")) -> Dict:
    loader = ProgramLoader(uart=None, verbose=False)

    fc1_w_1 = np.zeros((4, 16), dtype=np.int8)
    fc1_w_1[0, 0:4] = [1, -1, 2, 0]
    fc1_w_1[1, 0:4] = [0, 1, 1, -1]
    fc1_w_1[2, 0:4] = [-1, 0, 1, 1]
    fc1_w_1[3, 0:4] = [2, 1, 0, -2]
    x1 = np.zeros(16, dtype=np.int8)
    x1[0:4] = [2, -1, 1, 3]
    fc2_w_1 = np.zeros((4, 4), dtype=np.int8)
    fc2_w_1[0] = [1, 0, -1, 2]
    fc2_w_1[1] = [0, 2, 1, -1]
    fc2_w_1[2] = [1, 1, 1, 1]
    fc2_w_1[3] = [-1, 0, 2, 0]

    fc1_w_2 = np.zeros((4, 32), dtype=np.int8)
    fc1_w_2[0, 0:8] = [1, 1, -1, 0, 2, -2, 1, 0]
    fc1_w_2[0, 16:24] = [0, 1, 1, -1, 0, 2, -1, 1]
    fc1_w_2[1, 0:8] = [0, -1, 2, 1, -1, 0, 1, 1]
    fc1_w_2[1, 16:24] = [1, 0, -2, 1, 1, -1, 0, 2]
    fc1_w_2[2, 0:8] = [2, 0, 1, -1, 1, 1, 0, -2]
    fc1_w_2[2, 16:24] = [-1, 2, 0, 1, -1, 0, 1, 1]
    fc1_w_2[3, 0:8] = [1, -2, 0, 1, 0, 1, -1, 2]
    fc1_w_2[3, 16:24] = [2, 1, -1, 0, 1, -2, 1, 0]
    x2 = np.zeros(32, dtype=np.int8)
    x2[0:8] = [1, -1, 2, 0, -2, 1, 1, -1]
    x2[16:24] = [0, 2, -1, 1, 1, -2, 0, 1]
    fc2_w_2 = np.array([
        [1, -1, 2, 0],
        [0, 2, 1, -1],
        [1, 1, 0, 1],
        [-1, 0, 2, 1],
    ], dtype=np.int8)

    case1 = _build_case(loader, "case1_single_k", fc1_w_1, fc2_w_1, x1)
    case2 = _build_case(loader, "case2_multi_k", fc1_w_2, fc2_w_2, x2)

    summary = {
        "array_size": 16,
        "cases": [case1, case2],
    }
    os.makedirs(os.path.dirname(output_json), exist_ok=True)
    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    _write_svh(summary, os.path.join("build", "test_vectors", "fused_expected.svh"))
    return summary


if __name__ == "__main__":
    out = generate_vectors()
    print(json.dumps(out, indent=2))
