"""Phase 4 widened RTL testbench vector generator.

Builds a tiny INT8 single-block matmul (ARRAY_SIZE=8, COMPUTE_DATA_WIDTH=8,
ADDRESS_SIZE=12, EXT_ADDR_EN=1) using the new ``IsaConfig`` and writes:

* ``build/test_vectors/phase4_widen_program.mem``   -- program for $readmemh
* ``build/test_vectors/phase4_widen_expected.svh``  -- expected fetch bytes

The corresponding RTL testbench is ``rtl/tb/tb_phase4_widen.sv``.

Verification path: the python ``isa_simulator`` (which is exercised in
``firmware/host/test_phase4_isa_widen.py``) is the source of truth for the
expected bytes; we just emit the program + the bytes here so the iverilog
testbench can reproduce the same result on widened RTL.
"""

from __future__ import annotations

import os
from typing import List

import numpy as np

from isa_encoder import ISAEncoder, IsaConfig
from isa_simulator import simulate_program_bytes


ARRAY_SIZE = 8
ADDRESS_WIDTH = 12  # buffer_size = 4096 -> 12-bit addresses
COMPUTE_DATA_WIDTH = 8


def _build_program(W: np.ndarray, x: np.ndarray, cfg: IsaConfig, *,
                   array_size: int, weight_addr: int, input_addr: int,
                   result_addr: int, relu: bool) -> bytes:
    enc = ISAEncoder(cfg)
    items = cfg.items_per_word

    flat_w = W.flatten().tolist()
    addr = weight_addr
    for i in range(0, len(flat_w), items):
        enc.store(addr, flat_w[i : i + items])
        addr += 1
    enc.loadWeights(weight_addr)

    flat_x = x.flatten().tolist()
    addr = input_addr
    for i in range(0, len(flat_x), items):
        enc.store(addr, flat_x[i : i + items])
        addr += 1
    enc.loadInputs(input_addr)

    # Two-step RUN to match the RTL FSM:
    #   1) accumulate-only (compute=1, quantize=0, relu=0, acc_clear=1)
    #   2) finalize        (compute=0, quantize=1, relu=relu)
    # The python simulator's single fused RUN is functionally equivalent at
    # this widened cfg (verified in test_phase4_isa_widen).
    enc.run(result_addr, compute=True,  quantize=False, relu=False, acc_clear=True)
    enc.run(result_addr, compute=False, quantize=True,  relu=relu,  acc_clear=False)
    for widx in range(array_size // items):
        a = result_addr + widx
        enc.fetch(a, top_half=False)
        enc.fetch(a, top_half=True)
    enc.halt()
    return enc.getProgram()


def _write_mem(path: str, program: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for i in range(0, len(program), 2):
            word = int.from_bytes(program[i : i + 2], byteorder="little", signed=False)
            f.write(f"{word:04x}\n")


def _write_svh(path: str, *, mem_path: str, program_words: int,
               case1_bytes: List[int], case2_bytes: List[int]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mem_path = mem_path.replace("\\", "/")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_phase4_widen_rtl_vectors.py\n")
        f.write(f'`define P4_MEM "{mem_path}"\n')
        f.write(f"`define P4_WORDS {program_words}\n")
        f.write(f"`define P4_CASE1_FETCH_N {len(case1_bytes)}\n")
        for idx, val in enumerate(case1_bytes):
            f.write(f"`define P4_CASE1_EXP_BYTE_{idx} 8'h{val:02x}\n")
        f.write(f"`define P4_CASE2_FETCH_N {len(case2_bytes)}\n")
        for idx, val in enumerate(case2_bytes):
            f.write(f"`define P4_CASE2_EXP_BYTE_{idx} 8'h{val:02x}\n")


def main() -> None:
    cfg = IsaConfig(address_width=ADDRESS_WIDTH, compute_data_width=COMPUTE_DATA_WIDTH)

    # Banked-buffer addressing constraint: addresses for LOAD/RUN result writes
    # must be BANKS-aligned so successive addresses index successive banks
    # (consistent with how `unified_buffer.sv`'s `base_bank = address % BANKS`
    # interleaves data). For ARRAY_SIZE=8 INT8: BANKS = 64/2 = 32.
    banks = (ARRAY_SIZE * ARRAY_SIZE) // cfg.items_per_word

    weight_addr = 0
    input_addr_raw = weight_addr + (ARRAY_SIZE * ARRAY_SIZE) // cfg.items_per_word
    input_addr = ((input_addr_raw + banks - 1) // banks) * banks
    result_addr_raw = input_addr + ARRAY_SIZE // cfg.items_per_word
    result_addr = ((result_addr_raw + banks - 1) // banks) * banks

    rng = np.random.default_rng(0xBEEF)
    W1 = rng.integers(-50, 50, size=(ARRAY_SIZE, ARRAY_SIZE), dtype=np.int8)
    x1 = rng.integers(-50, 50, size=(ARRAY_SIZE,), dtype=np.int8)

    prog1 = _build_program(
        W1, x1, cfg=cfg, array_size=ARRAY_SIZE,
        weight_addr=weight_addr, input_addr=input_addr, result_addr=result_addr,
        relu=False,
    )
    sim1 = simulate_program_bytes(
        prog1, array_size=ARRAY_SIZE, buffer_size=4096, cfg=cfg,
        accumulator_data_width=32,
    )
    assert sim1.halted, "simulator must halt on the widened INT8 program"

    mem_path = os.path.join("build", "test_vectors", "phase4_widen_program.mem")
    _write_mem(mem_path, prog1)

    svh_path = os.path.join("build", "test_vectors", "phase4_widen_expected.svh")
    _write_svh(
        svh_path,
        mem_path=mem_path,
        program_words=len(prog1) // 2,
        case1_bytes=sim1.fetch_bytes,
        case2_bytes=sim1.fetch_bytes,
    )
    print(f"Wrote {mem_path} ({len(prog1)//2} words) and {svh_path}")
    print(f"Expected fetch bytes: {[f'0x{b:02x}' for b in sim1.fetch_bytes]}")


if __name__ == "__main__":
    main()
