from __future__ import annotations

import json
import os
from typing import Dict, List

import numpy as np

from isa_encoder import DEFAULT_CFG, IsaConfig
from isa_simulator import simulate_program_bytes
from lowering_blocked_fc_utpu import lower_blocked_fc_program_utpu
from requantization import RequantParams


ARRAY_SIZE = 16
LEGACY_CFG = DEFAULT_CFG
BATCHED_CFG = IsaConfig(address_width=12, compute_data_width=4)
LEGACY_BUFFER_SIZE = 512
BATCHED_BUFFER_SIZE = 1 << BATCHED_CFG.address_width
LEGACY_WEIGHT_ADDR = 256
LEGACY_INPUT_ADDR = 0
LEGACY_RESULT_ADDR = 320
BATCHED_WEIGHT_ADDR = 0
BATCHED_INPUT_ADDR = 128
BATCHED_RESULT_ADDR = 256
DEFAULT_BATCH_SIZE = 4


def _write_program_mem(path: str, program: bytes) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for i in range(0, len(program), 2):
            word = int.from_bytes(program[i:i + 2], byteorder="little", signed=False)
            f.write(f"{word:04x}\n")


def _write_expected_fetch_mem(path: str, fetch_bytes: List[int]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for val in fetch_bytes:
            f.write(f"{int(val) & 0xFF:02x}\n")


def _write_svh(
    path: str,
    *,
    mem_path: str,
    expected_fetch_mem_path: str,
    program_words: int,
    fetch_bytes: List[int],
    array_size: int,
    buffer_size: int,
    prog_depth: int,
    ext_addr_en: int,
    compute_data_width: int,
    accumulator_data_width: int,
) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mem_path = mem_path.replace("\\", "/")
    expected_fetch_mem_path = expected_fetch_mem_path.replace("\\", "/")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_batched_gemm_rtl_vectors.py\n")
        f.write(f'`define BG_MEM "{mem_path}"\n')
        f.write(f'`define BG_FETCH_MEM "{expected_fetch_mem_path}"\n')
        f.write(f"`define BG_WORDS {program_words}\n")
        f.write(f"`define BG_FETCH_N {len(fetch_bytes)}\n")
        f.write(f"`define BG_ARRAY_SIZE {array_size}\n")
        f.write(f"`define BG_BUFFER_SIZE {buffer_size}\n")
        f.write(f"`define BG_PROG_DEPTH {prog_depth}\n")
        f.write(f"`define BG_EXT_ADDR_EN {ext_addr_en}\n")
        f.write(f"`define BG_COMPUTE_DATA_WIDTH {compute_data_width}\n")
        f.write(f"`define BG_ACCUMULATOR_DATA_WIDTH {accumulator_data_width}\n")


def generate_vectors(
    *,
    out_features: int = ARRAY_SIZE,
    in_features: int = ARRAY_SIZE,
    batch_size: int = DEFAULT_BATCH_SIZE,
    stem: str = "batched_gemm",
    output_json: str = os.path.join("build", "test_vectors", "batched_gemm_expected.json"),
    hoist_tile_payloads: bool = False,
    cfg: IsaConfig | None = None,
    buffer_size: int | None = None,
    weight_addr: int | None = None,
    input_addr: int | None = None,
    result_addr: int | None = None,
    accumulator_data_width: int = 32,
    requant_params: RequantParams | None = None,
) -> Dict[str, object]:
    seed = 0xBA7C + out_features * 37 + in_features * 13 + batch_size
    rng = np.random.default_rng(seed)
    weights = rng.integers(-8, 8, size=(out_features, in_features), dtype=np.int8)
    activations = rng.integers(-8, 8, size=(batch_size, in_features), dtype=np.int8)
    cfg = cfg if cfg is not None else (LEGACY_CFG if batch_size == 1 else BATCHED_CFG)
    buffer_size = buffer_size if buffer_size is not None else (LEGACY_BUFFER_SIZE if batch_size == 1 else BATCHED_BUFFER_SIZE)
    weight_addr = weight_addr if weight_addr is not None else (LEGACY_WEIGHT_ADDR if batch_size == 1 else BATCHED_WEIGHT_ADDR)
    input_addr = input_addr if input_addr is not None else (LEGACY_INPUT_ADDR if batch_size == 1 else BATCHED_INPUT_ADDR)
    result_addr = result_addr if result_addr is not None else (LEGACY_RESULT_ADDR if batch_size == 1 else BATCHED_RESULT_ADDR)

    lowered = lower_blocked_fc_program_utpu(
        weights,
        activations,
        out_features,
        in_features,
        ARRAY_SIZE,
        False,
        True,
        weight_addr,
        input_addr,
        result_addr,
        cfg=cfg,
        hoist_tile_payloads=hoist_tile_payloads,
        requant_params=requant_params,
    )
    sim = simulate_program_bytes(
        lowered["program"],
        array_size=ARRAY_SIZE,
        buffer_size=buffer_size,
        cfg=cfg,
        accumulator_data_width=accumulator_data_width,
    )
    assert sim.halted, "batched GEMM simulator program must halt"
    prog_words = len(lowered["program"]) // 2
    prog_depth = max(1024, int(prog_words) + 16)

    mem_path = os.path.join("build", "test_vectors", f"{stem}_program.mem")
    expected_fetch_mem_path = os.path.join("build", "test_vectors", f"{stem}_fetch_expected.mem")
    _write_program_mem(mem_path, lowered["program"])
    _write_expected_fetch_mem(expected_fetch_mem_path, list(sim.fetch_bytes))
    _write_svh(
        os.path.join("build", "test_vectors", "batched_gemm_expected.svh"),
        mem_path=mem_path,
        expected_fetch_mem_path=expected_fetch_mem_path,
        program_words=prog_words,
        fetch_bytes=sim.fetch_bytes,
        array_size=ARRAY_SIZE,
        buffer_size=buffer_size,
        prog_depth=prog_depth,
        ext_addr_en=1 if cfg.extended_address else 0,
        compute_data_width=cfg.compute_data_width,
        accumulator_data_width=accumulator_data_width,
    )

    payload: Dict[str, object] = {
        "array_size": ARRAY_SIZE,
        "out_features": int(out_features),
        "in_features": int(in_features),
        "batch_size": int(batch_size),
        "cfg": {
            "address_width": cfg.address_width,
            "compute_data_width": cfg.compute_data_width,
            "buffer_size": buffer_size,
            "extended_address": bool(cfg.extended_address),
        },
        "accumulator_data_width": int(accumulator_data_width),
        "program_mem": mem_path,
        "expected_fetch_mem": expected_fetch_mem_path,
        "program_words": prog_words,
        "prog_depth": int(prog_depth),
        "expected_fetch_bytes": list(sim.fetch_bytes),
        "program_instruction_words": int(lowered["program_instruction_words"]),
        "out_blocks": int(lowered["out_blocks"]),
        "in_blocks": int(lowered["in_blocks"]),
        "useful_macs": int(out_features) * int(in_features) * int(batch_size),
        "hoist_tile_payloads": bool(lowered["hoist_tile_payloads"]),
        "requant_params": requant_params.as_dict() if requant_params is not None else None,
    }
    os.makedirs(os.path.dirname(output_json), exist_ok=True)
    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    return payload


if __name__ == "__main__":
    print(json.dumps(generate_vectors(), indent=2))
