from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from cuda_blocked_fc_backend import CUDAGraphOpExecutor
from diff_oracle import compare, register_backend, run_all_backends
from graph_ir import GraphIR, OpKind, OpNode
from graph_reference_interpreter import GraphReferenceInterpreter
from isa_encoder import IsaConfig
from requantization import RequantParams
from run_rtl_batched_gemm_sim import _iverilog_run, _parse_perf_counter, _resolve_iverilog_tools
from utpu_conv2d_lowering import DEFAULT_CONV_CFG, simulate_lowered_conv2d_utpu


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_JSON = REPO_ROOT / "bench" / "results" / "utpu_conv2d_validation.json"
ARRAY_SIZE = 16
REQUANT_IDENTITY = RequantParams(multiplier=1, right_shift=0, enable=True)


@dataclass(frozen=True)
class ConvCase:
    name: str
    input_shape: Tuple[int, int, int, int]
    weight_shape: Tuple[int, int, int, int]
    stride: Tuple[int, int]
    padding: Tuple[int, int]


CORRECTNESS_CASES: Tuple[ConvCase, ...] = (
    ConvCase("conv_k3_same", (1, 1, 4, 4), (2, 1, 3, 3), (1, 1), (1, 1)),
    ConvCase("conv_stride2", (1, 2, 6, 6), (3, 2, 3, 3), (2, 2), (1, 1)),
    ConvCase("conv_k1", (1, 3, 5, 5), (4, 3, 1, 1), (1, 1), (0, 0)),
    ConvCase("conv_valid", (1, 4, 7, 7), (2, 4, 3, 3), (2, 2), (0, 0)),
)

RTL_CASES: Tuple[str, ...] = ("conv_k3_same", "conv_stride2")


def _make_integer_tensor(shape: Sequence[int], *, seed: int) -> np.ndarray:
    rng = np.random.default_rng(int(seed))
    return rng.integers(low=-1, high=2, size=tuple(int(v) for v in shape), dtype=np.int8).astype(np.float32)


def _build_graph(case: ConvCase) -> Tuple[GraphIR, np.ndarray]:
    x = _make_integer_tensor(case.input_shape, seed=100 + len(case.name))
    w = _make_integer_tensor(case.weight_shape, seed=200 + len(case.name))
    graph = GraphIR(name=case.name)
    graph.inputs = ["x"]
    graph.outputs = ["y"]
    graph.add_value("x", shape=case.input_shape, dtype="torch.float32")
    graph.add_op(
        OpNode(
            name="conv",
            op=OpKind.CONV2D,
            inputs=["x"],
            outputs=["y"],
            attrs={
                "weight": w,
                "bias": None,
                "stride": case.stride,
                "padding": case.padding,
                "dilation": (1, 1),
                "groups": 1,
            },
        )
    )
    return graph, x


def _write_program_mem(path: Path, program: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for i in range(0, len(program), 2):
            word = int.from_bytes(program[i : i + 2], byteorder="little", signed=False)
            f.write(f"{word:04x}\n")


def _write_expected_fetch_mem(path: Path, fetch_bytes: Sequence[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for val in fetch_bytes:
            f.write(f"{int(val) & 0xFF:02x}\n")


def _write_batched_svh(
    *,
    mem_path: Path,
    expected_fetch_mem_path: Path,
    program_words: int,
    fetch_bytes: Sequence[int],
    cfg: IsaConfig,
) -> None:
    svh_path = REPO_ROOT / "build" / "test_vectors" / "batched_gemm_expected.svh"
    svh_path.parent.mkdir(parents=True, exist_ok=True)
    mem_str = str(mem_path).replace("\\", "/")
    fetch_str = str(expected_fetch_mem_path).replace("\\", "/")
    with svh_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by run_utpu_conv2d_validation.py\n")
        f.write(f'`define BG_MEM "{mem_str}"\n')
        f.write(f'`define BG_FETCH_MEM "{fetch_str}"\n')
        f.write(f"`define BG_WORDS {program_words}\n")
        f.write(f"`define BG_FETCH_N {len(fetch_bytes)}\n")
        f.write(f"`define BG_ARRAY_SIZE {ARRAY_SIZE}\n")
        f.write(f"`define BG_BUFFER_SIZE {1 << cfg.address_width}\n")
        f.write(f"`define BG_PROG_DEPTH {max(1024, program_words + 16)}\n")
        f.write(f"`define BG_EXT_ADDR_EN {1 if cfg.extended_address else 0}\n")
        f.write(f"`define BG_COMPUTE_DATA_WIDTH {cfg.compute_data_width}\n")
        f.write("`define BG_ACCUMULATOR_DATA_WIDTH 32\n")


def _run_single_program_rtl(program: bytes, expected_fetch_bytes: Sequence[int], stem: str) -> Dict[str, Any]:
    mem_path = REPO_ROOT / "build" / "test_vectors" / f"{stem}.mem"
    fetch_path = REPO_ROOT / "build" / "test_vectors" / f"{stem}_fetch.mem"
    _write_program_mem(mem_path, program)
    _write_expected_fetch_mem(fetch_path, expected_fetch_bytes)
    _write_batched_svh(
        mem_path=mem_path,
        expected_fetch_mem_path=fetch_path,
        program_words=len(program) // 2,
        fetch_bytes=expected_fetch_bytes,
        cfg=DEFAULT_CONV_CFG,
    )
    ok, log = _iverilog_run(str(REPO_ROOT))
    return {
        "rtl_sim_executed": "not found" not in (log or ""),
        "rtl_sim_passed": bool(ok),
        "program_instruction_words": len(program) // 2,
        "perf_cycle_counter": _parse_perf_counter(log, "PERF_CYCLE_COUNTER"),
        "perf_busy_counter": _parse_perf_counter(log, "PERF_BUSY_COUNTER"),
        "compute_busy_cycles": _parse_perf_counter(log, "COMPUTE_BUSY_CYCLES"),
        "compute_span_cycles": _parse_perf_counter(log, "COMPUTE_SPAN_CYCLES"),
    }


def _register_case_backends(case: ConvCase, graph: GraphIR, x: np.ndarray) -> None:
    def _cuda_graph_runner(_graph: GraphIR, inputs: Sequence[Any], **_: Any) -> np.ndarray:
        result = CUDAGraphOpExecutor(device="cuda").run(_graph, *inputs)
        if not result.get("executed", False):
            raise RuntimeError(result.get("reason", "cuda graph execution failed"))
        return np.asarray(result["outputs"], dtype=np.float32)

    def _utpu_conv_runner(_graph: GraphIR, inputs: Sequence[Any], **_: Any) -> np.ndarray:
        conv = next(op for op in _graph.ops if op.op == OpKind.CONV2D)
        result = simulate_lowered_conv2d_utpu(
            inputs[0],
            conv.attrs["weight"],
            bias=conv.attrs.get("bias"),
            stride=conv.attrs.get("stride", 1),
            padding=conv.attrs.get("padding", 0),
            dilation=conv.attrs.get("dilation", 1),
            groups=int(conv.attrs.get("groups", 1)),
            array_size=ARRAY_SIZE,
            cfg=DEFAULT_CONV_CFG,
            requant_params=REQUANT_IDENTITY,
        )
        return np.asarray(result["output"], dtype=np.float32)

    register_backend(f"cuda_graph_{case.name}", _cuda_graph_runner)
    register_backend(f"utpu_conv_isa_{case.name}", _utpu_conv_runner)


def _evaluate_case(case: ConvCase) -> Dict[str, Any]:
    graph, x = _build_graph(case)
    conv = graph.ops[0]
    oracle = np.asarray(GraphReferenceInterpreter(graph).run(x), dtype=np.float32)
    utpu = simulate_lowered_conv2d_utpu(
        x,
        conv.attrs["weight"],
        bias=conv.attrs.get("bias"),
        stride=conv.attrs.get("stride", 1),
        padding=conv.attrs.get("padding", 0),
        dilation=conv.attrs.get("dilation", 1),
        groups=int(conv.attrs.get("groups", 1)),
        array_size=ARRAY_SIZE,
        cfg=DEFAULT_CONV_CFG,
        requant_params=REQUANT_IDENTITY,
    )
    _register_case_backends(case, graph, x)
    outputs = run_all_backends(
        graph,
        [x],
        backends=("numpy_reference", f"cuda_graph_{case.name}", f"utpu_conv_isa_{case.name}"),
    )
    cmp = compare(outputs, rtol=0.0, atol=0.0)

    entry: Dict[str, Any] = {
        "name": case.name,
        "input_shape": list(case.input_shape),
        "weight_shape": list(case.weight_shape),
        "stride": list(case.stride),
        "padding": list(case.padding),
        "mapping": utpu["mapping"],
        "program_count": len(utpu["lowered"].programs),
        "program_instruction_words": [int(p.program_instruction_words) for p in utpu["lowered"].programs],
        "oracle_shape": list(oracle.shape),
        "utpu_bit_exact_vs_oracle": bool(np.array_equal(oracle, utpu["output"])),
        "all_programs_bit_exact_vs_oracle": bool(utpu["all_programs_bit_exact_vs_oracle"]),
        "parity": cmp.to_dict(),
    }
    if case.name in RTL_CASES and len(utpu["lowered"].programs) == 1:
        entry["rtl"] = _run_single_program_rtl(
            utpu["lowered"].programs[0].program,
            utpu["lowered"].programs[0].expected_fetch_bytes,
            stem=f"utpu_conv_{case.name}",
        )
    else:
        entry["rtl"] = {
            "rtl_sim_executed": False,
            "rtl_sim_passed": False,
            "skip_reason": "case not selected for RTL gate or lowering produced multiple programs",
        }
    return entry


def build_report(output_json: Path = OUTPUT_JSON) -> Dict[str, Any]:
    cases = [_evaluate_case(case) for case in CORRECTNESS_CASES]
    rtl_cases = [case for case in cases if case["name"] in RTL_CASES]
    report = {
        "generated_at_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "mapping_choice": {
            "strategy": "im2col",
            "why": (
                "The current uTPU datapath already exposes batched blocked-FC GEMM plus finalize requant. "
                "im2col lets conv2d reuse that real lowering/ISA path immediately. The tradeoff is activation "
                "materialization blowup proportional to kernel_area * output_positions, which is acceptable for "
                "this bounded one-layer simulation phase but not the long-term memory story."
            ),
        },
        "where_mapping_happens": "firmware/host/utpu_conv2d_lowering.py::lower_conv2d_im2col_utpu",
        "cfg": {
            "address_width": DEFAULT_CONV_CFG.address_width,
            "compute_data_width": DEFAULT_CONV_CFG.compute_data_width,
            "requant_multiplier": REQUANT_IDENTITY.multiplier,
            "requant_right_shift": REQUANT_IDENTITY.right_shift,
        },
        "cases": cases,
        "gates": {
            "correctness_pass_count": int(sum(1 for case in cases if case["utpu_bit_exact_vs_oracle"])),
            "correctness_total_count": int(len(cases)),
            "rtl_pass_count": int(sum(1 for case in rtl_cases if case["rtl"].get("rtl_sim_passed"))),
            "rtl_total_count": int(len(rtl_cases)),
            "backend_parity_pass_count": int(sum(1 for case in cases if case["parity"]["all_bit_exact"])),
            "backend_parity_total_count": int(len(cases)),
            "iverilog_available": bool(_resolve_iverilog_tools()[0] and _resolve_iverilog_tools()[1]),
        },
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
    return report


def main() -> int:
    report = build_report()
    print(
        json.dumps(
            {
                "output_json": str(OUTPUT_JSON),
                "correctness": f"{report['gates']['correctness_pass_count']}/{report['gates']['correctness_total_count']}",
                "rtl": f"{report['gates']['rtl_pass_count']}/{report['gates']['rtl_total_count']}",
                "backend_parity": f"{report['gates']['backend_parity_pass_count']}/{report['gates']['backend_parity_total_count']}",
                "where_mapping_happens": report["where_mapping_happens"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
