"""Task 2 fuzzer driver — emits ``bench/results/fuzzer_report.json``.

Runs the generator + metamorphic + differential pipeline for ``--num-graphs``
seeds, classifies each divergence (real miscompile vs tolerance artifact),
minimizes any failing graph to a minimal reproducer, and writes a single
JSON artifact. The artifact schema is locked by ``test_fuzzer.py`` so docs
can rely on the structure even when zero bugs are found.

Modes:
  --mode ci_seeded   : short deterministic run (default --num-graphs 64).
                       Seed range starts at --seed (default 1234).
                       Used by ``make test-host`` and CI as a gate.
  --mode discovery   : long discovery run (e.g. --num-graphs 10000).
                       Used locally to discover real bugs; commits any
                       minimized repro into firmware/host/fuzz/repros/.

Honesty contract:
  - Bugs found ARE reported. Bugs not found are not invented.
  - The artifact's ``num_real_miscompiles`` is exactly the number of
    minimized failures the run actually produced.
  - The planted-bug test is in ``test_fuzzer.py``, NOT in this driver,
    so the artifact never claims to have caught the planted bug as a
    "real" miscompile.
  - Invalid-graph rejection counts are tracked SEPARATELY from
    equivalence checks so the headline "0 miscompiles" claim stays
    apples-to-apples.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import random
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

HOST_DIR = os.path.dirname(os.path.abspath(__file__))
if HOST_DIR not in sys.path:
    sys.path.insert(0, HOST_DIR)

from fuzz import differential_oracle as fdo  # noqa: E402
from fuzz.graph_generator import (  # noqa: E402
    ALL_GRAPH_FAMILIES,
    GeneratedProgram,
    assert_program_legal,
    coverage_summary,
    generate_program,
)
from fuzz.input_distributions import (  # noqa: E402
    DISTRIBUTIONS as INPUT_DISTRIBUTIONS,
    apply_to_program,
    coverage_summary as input_distribution_coverage,
    pick_distribution,
)
from fuzz.invalid_generator import (  # noqa: E402
    INVALID_KINDS,
    check_rejection,
    generate_invalid_program,
    invalid_coverage_summary,
)
from fuzz.metamorphic import (  # noqa: E402
    ALL_RELATIONS,
    MetamorphicResult,
    evaluate_all_relations,
)
from fuzz.minimizer import minimize  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_JSON = REPO_ROOT / "bench" / "results" / "fuzzer_report.json"
REPROS_DIR = Path(HOST_DIR) / "fuzz" / "repros"

DEFAULT_NUM_GRAPHS_CI = 64
DEFAULT_NUM_GRAPHS_DISCOVERY = 10_000
DEFAULT_SEED = 1234

# Default fraction of invalid graphs in --include-invalid runs. The invalid
# corpus is generated by walking a parallel seed stream so the valid corpus
# count remains exactly --num-graphs.
DEFAULT_INVALID_FRACTION = 0.20

# Tolerance defaults. Float relations use the project standard
# (rtol=atol=1e-3, matching megakernel + differential_test_harness).
# The strict bit-exact gate is only applied to relations that are
# logically integer-equal (tiling_AB).
DEFAULT_RTOL = 1e-3
DEFAULT_ATOL = 1e-3

# Schema version. v3 (this hardening pass) adds:
#   - num_valid_graphs_generated / num_invalid_graphs_generated
#   - num_equivalence_checks / num_rejection_checks
#   - num_invalid_graphs_rejected_cleanly / unexpectedly_accepted / crashed_badly
#   - graph_families_covered / input_distributions_covered
#   - relation_evaluation_counts / skip_rate_by_relation
#   - invalid_kinds_covered / invalid_rejection_outcomes (per-kind histogram)
SCHEMA_VERSION = 3


def _git_sha() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, cwd=str(REPO_ROOT)
        ).strip()
        return out or "unknown"
    except Exception:
        return "unknown"


def _host_environment() -> Dict[str, Any]:
    env: Dict[str, Any] = {
        "python_version": platform.python_version(),
        "platform": platform.platform(),
        "numpy_version": np.__version__,
    }
    try:
        import torch  # type: ignore

        env["torch_version"] = torch.__version__
    except Exception:
        env["torch_version"] = None
    return env


# Regexes used to bucket free-form `skip_reason` strings into a stable
# histogram. Buckets are intentionally coarse so 5000+ skip events fold
# into a handful of human-readable rows, not 5000 unique strings.
# Order matters: the first matching needle wins, so put more-specific
# substrings first.
_SKIP_REASON_BUCKETS: List[Tuple[str, str]] = [
    # ---- region_fused_vs_op_by_op (order matters: more-specific FIRST) ----
    ("region.output != graph.outputs", "region_not_whole_graph"),
    ("region produces", "region_not_whole_graph"),
    ("region's tensor", "region_not_whole_graph"),
    ("multi-output convention", "region_multi_output_unsupported"),
    ("graph has 0 fusable regions", "no_fusable_region"),
    ("v1 runs single-region only", "multi_region_unsupported_v1"),
    ("cuda_megakernel runner missing", "cuda_megakernel_runner_missing"),
    ("cuda_megakernel skipped", "cuda_megakernel_runner_rejected_region_kind"),
    ("cuda_megakernel raised", "cuda_megakernel_runner_runtime_error"),
    ("cuda_megakernel unavailable", "cuda_megakernel_unavailable"),
    ("cuda-python", "cuda_megakernel_unavailable"),
    ("region_fusion import failed", "region_fusion_import_failed"),
    ("diff_oracle backend lookup failed", "diff_oracle_backend_lookup_failed"),
    ("numpy_reference unavailable", "numpy_reference_unavailable"),
    ("numpy_reference raised", "numpy_reference_runtime_error"),
    ("splice execution raised", "splice_runtime_error"),
    # ---- fusion_on_off ----
    ("no LINEAR->RELU pair", "no_linear_relu_pattern"),
    ("no LINEAR -> RELU", "no_linear_relu_pattern"),
    ("no LINEAR_RELU op", "no_linear_relu_pattern"),
    ("no fusable LINEAR", "no_linear_relu_pattern"),
    # ---- dce_on_off ----
    ("no dead code", "no_dead_code_to_eliminate"),
    ("no dead op", "no_dead_code_to_eliminate"),
    # ---- schedule_alternative ----
    ("cost_model unavailable", "cost_model_unavailable"),
    ("cost_model.select failed", "cost_model_select_failed"),
    ("no LINEAR/LINEAR_RELU op", "no_linear_op"),
    ("no LINEAR op", "no_linear_op"),
    ("linear weight not 2-D", "linear_weight_not_2d"),
    ("schedule alternative not available", "no_legal_schedule_alternative"),
    ("only one schedule legal", "no_legal_schedule_alternative"),
    ("cost_model returned only one option", "no_legal_schedule_alternative"),
    ("only one viable schedule", "no_legal_schedule_alternative"),
    # ---- tiling_AB ----
    ("only one legal tile size", "no_legal_tile_alternative"),
    ("could not produce a distinct second tile", "no_legal_tile_alternative"),
    ("plan_b unchanged", "no_legal_tile_alternative"),
    ("tiling_controller unavailable", "tiling_controller_unavailable"),
    ("input shape", "input_shape_mismatch"),
    # ---- generic / shared ----
    ("unknown relation", "unknown_relation"),
]


def _normalize_skip_reason(reason: Optional[str]) -> str:
    """Map a free-form `skip_reason` to a stable histogram bucket label."""
    if not reason:
        return "unknown"
    text = reason.lower()
    for needle, bucket in _SKIP_REASON_BUCKETS:
        if needle.lower() in text:
            return bucket
    return "other"


def _classify_divergence(results: List[MetamorphicResult]) -> Tuple[bool, List[str]]:
    """Return (any_real_failure, [relation names that failed]).

    A failure is "real" when `match=False` AND `skipped=False`. The
    distinction matters for `num_real_miscompiles` vs
    `num_tolerance_artifacts` in the artifact.
    """
    failed = [r.relation for r in results if not r.match and not r.skipped]
    return (len(failed) > 0, failed)


def _failing_relation_predicate(failing_relations: List[str], rtol: float, atol: float):
    """Build a predicate the minimizer can call on candidate programs."""

    def predicate(p: GeneratedProgram) -> bool:
        try:
            assert_program_legal(p)
        except AssertionError:
            return False
        try:
            results = evaluate_all_relations(
                p, relations=tuple(failing_relations), rtol=rtol, atol=atol
            )
        except Exception:
            return False
        for r in results:
            if not r.match and not r.skipped:
                return True
        return False

    return predicate


def _emit_repro_for_bug(
    bug_id: str,
    program: GeneratedProgram,
    failing_relations: List[str],
    repros_dir: Path,
) -> Tuple[str, str]:
    """Write a self-contained reproducer + a regression test under `repros_dir`."""
    repros_dir.mkdir(parents=True, exist_ok=True)
    g = program.graph
    op_lines: List[str] = []
    for op in g.ops:
        attr_strs: List[str] = []
        for k, v in op.attrs.items():
            if isinstance(v, np.ndarray):
                attr_strs.append(f'"{k}": np.array({v.tolist()!r}, dtype=np.float32)')
            elif isinstance(v, (int, float, bool, str)) or v is None:
                attr_strs.append(f'"{k}": {v!r}')
            else:
                attr_strs.append(f'"{k}": {v!r}')
        attrs_repr = "{" + ", ".join(attr_strs) + "}"
        op_lines.append(
            f'    g.add_op(OpNode(name={op.name!r}, op={op.op!r}, '
            f'inputs={list(op.inputs)!r}, outputs={list(op.outputs)!r}, '
            f'attrs={attrs_repr}))'
        )
    inputs_arr = []
    for arr in program.inputs:
        inputs_arr.append(f"    np.array({np.asarray(arr).tolist()!r}, dtype=np.float32)")

    repro_content = (
        f'"""Auto-generated reproducer for {bug_id}.\n\n'
        f'Failing metamorphic relations: {failing_relations!r}.\n'
        'Built by `firmware/host/run_fuzzer.py` after delta-debugging.\n'
        '"""\n\n'
        'from __future__ import annotations\n\n'
        'import numpy as np\n\n'
        'from graph_ir import GraphIR, OpNode\n\n\n'
        'def build_program():\n'
        f'    g = GraphIR(name={g.name!r})\n'
        f'    g.inputs = {list(g.inputs)!r}\n'
        f'    g.outputs = {list(g.outputs)!r}\n'
        '    for name in g.inputs:\n'
        '        g.add_value(name)\n'
    )
    repro_content += "\n".join(op_lines) + "\n"
    repro_content += '    inputs = [\n' + ",\n".join(inputs_arr) + ",\n    ]\n"
    repro_content += '    return g, inputs\n'
    test_content = (
        f'"""Regression test for {bug_id} (auto-generated)."""\n\n'
        'from fuzz.graph_generator import GeneratedProgram\n'
        'from fuzz.metamorphic import evaluate_all_relations\n'
        f'from fuzz.repros.{bug_id} import build_program\n\n\n'
        f'def test_{bug_id}_metamorphic_failure_reproduces():\n'
        '    graph, inputs = build_program()\n'
        '    program = GeneratedProgram(seed=-1, graph=graph, inputs=inputs)\n'
        f'    failing = {failing_relations!r}\n'
        '    results = evaluate_all_relations(program, relations=failing)\n'
        '    real = [r for r in results if not r.match and not r.skipped]\n'
        '    assert real, (\n'
        '        f"expected {failing} to fail on this minimized graph, "\n'
        '        f"but every relation passed — the bug may be fixed; if so, "\n'
        '        f"close the bug and remove this regression test"\n'
        '    )\n'
    )
    repro_path = repros_dir / f"{bug_id}.py"
    test_path = repros_dir / f"test_{bug_id}.py"
    repro_path.write_text(repro_content, encoding="utf-8")
    test_path.write_text(test_content, encoding="utf-8")
    return str(repro_path.relative_to(REPO_ROOT)), str(test_path.relative_to(REPO_ROOT))


def _build_artifact_skeleton(
    mode: str,
    seed: int,
    num_graphs: int,
    include_invalid: bool,
    include_torch_inductor: bool = False,
) -> Dict[str, Any]:
    return {
        "status": "ok",
        "schema_version": SCHEMA_VERSION,
        "mode": mode,
        "seed": int(seed),
        # ---- Valid corpus counters ----
        "num_graphs_generated": 0,
        "num_graphs_evaluated": 0,
        "num_valid_graphs_generated": 0,
        # ---- Invalid corpus counters ----
        "num_invalid_graphs_generated": 0,
        "num_invalid_graphs_rejected_cleanly": 0,
        "num_invalid_graphs_unexpectedly_accepted": 0,
        "num_invalid_graphs_crashed_badly": 0,
        # ---- Aggregate check counters ----
        "num_equivalence_checks": 0,
        "inductor_checks": 0,
        "inductor_skips": 0,
        "include_torch_inductor": bool(include_torch_inductor),
        "num_rejection_checks": 0,
        "num_divergences_found": 0,
        "num_real_miscompiles": 0,
        "num_tolerance_artifacts": 0,
        # ---- Discovery artifacts ----
        "bugs": [],
        "invalid_findings": [],
        "relations": list(ALL_RELATIONS),
        "relation_stats": {
            r: {"evaluated": 0, "skipped": 0, "failed": 0} for r in ALL_RELATIONS
        },
        "relation_evaluation_counts": {r: 0 for r in ALL_RELATIONS},
        "skip_rate_by_relation": {r: 0.0 for r in ALL_RELATIONS},
        # `skipped_relation_reasons` is a per-relation histogram of skip
        # reasons. The buckets are stable strings derived from the
        # `MetamorphicResult.skip_reason` text so reviewers can see
        # *why* a relation didn't fire (e.g. "graph has 0 fusable
        # regions" vs "cuda_megakernel unavailable" vs the
        # region/graph-output mismatch guard added 2026-05-25).
        "skipped_relation_reasons": {r: {} for r in ALL_RELATIONS},
        "coverage": {
            "ops_covered": [],
            "shape_buckets_covered": [],
            "kinds_covered": [],
            "graph_families_covered": [],
            "input_distributions_covered": [],
            "input_distribution_counts": {d: 0 for d in INPUT_DISTRIBUTIONS},
            "invalid_kinds_covered": [],
            "invalid_validators_covered": [],
            "pass_branch_coverage_pct": None,
            "pass_branch_coverage_note": (
                "compiler-pass branch coverage via coverage.py is recorded only when "
                "coverage.py is installed AND the runner is invoked with --measure-coverage. "
                "The cheaper generator-side coverage (ops/shape buckets/kinds/distributions) "
                "is always populated."
            ),
        },
        "invalid_rejection_outcomes": {
            kind: {"rejected_cleanly": 0, "unexpectedly_accepted": 0, "crashed_badly": 0}
            for kind in INVALID_KINDS
        },
        "environment": _host_environment(),
        "git_sha": _git_sha(),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "tolerance": {"rtol": DEFAULT_RTOL, "atol": DEFAULT_ATOL},
        "cuda_megakernel_registered": False,
        "cuda_megakernel_skip_reason": None,
        "num_graphs_requested": int(num_graphs),
        "include_invalid": bool(include_invalid),
        "errors": [],
    }


def _update_relation_stats(
    artifact: Dict[str, Any], results: List[MetamorphicResult]
) -> None:
    for r in results:
        entry = artifact["relation_stats"][r.relation]
        if r.skipped:
            entry["skipped"] += 1
            bucket = _normalize_skip_reason(r.skip_reason)
            hist = artifact["skipped_relation_reasons"][r.relation]
            hist[bucket] = hist.get(bucket, 0) + 1
        else:
            entry["evaluated"] += 1
            if not r.match:
                entry["failed"] += 1
        artifact["relation_evaluation_counts"][r.relation] += 1


def _finalize_skip_rates(artifact: Dict[str, Any]) -> None:
    for r in ALL_RELATIONS:
        total = artifact["relation_evaluation_counts"][r]
        skipped = artifact["relation_stats"][r]["skipped"]
        artifact["skip_rate_by_relation"][r] = (
            float(skipped) / float(total) if total > 0 else 0.0
        )


def _run_invalid_pass(
    artifact: Dict[str, Any],
    invalid_seed: int,
    num_invalid: int,
    max_findings_records: int = 64,
) -> None:
    """Generate invalid graphs and verify the compiler rejects each cleanly."""
    rng_pick = random.Random(int(invalid_seed))
    for i in range(int(num_invalid)):
        s = int(invalid_seed) + i
        kind = INVALID_KINDS[i % len(INVALID_KINDS)] if i < 4 * len(INVALID_KINDS) else rng_pick.choice(INVALID_KINDS)
        try:
            program = generate_invalid_program(s, kind=kind)
        except Exception as e:  # noqa: BLE001
            artifact["errors"].append(
                f"invalid_seed={s} kind={kind!r}: invalid generator failure: {type(e).__name__}: {e}"
            )
            continue
        artifact["num_invalid_graphs_generated"] += 1
        artifact["num_rejection_checks"] += 1
        outcome = check_rejection(program)
        bucket = artifact["invalid_rejection_outcomes"][outcome.invalid_kind]
        if outcome.rejected_cleanly:
            bucket["rejected_cleanly"] += 1
            artifact["num_invalid_graphs_rejected_cleanly"] += 1
        elif outcome.unexpectedly_accepted:
            bucket["unexpectedly_accepted"] += 1
            artifact["num_invalid_graphs_unexpectedly_accepted"] += 1
            if len(artifact["invalid_findings"]) < max_findings_records:
                artifact["invalid_findings"].append(
                    {
                        "seed": int(s),
                        "kind": outcome.invalid_kind,
                        "validator": outcome.validator,
                        "outcome": "unexpectedly_accepted",
                        "exception_type": None,
                        "exception_message": None,
                    }
                )
        elif outcome.crashed_badly:
            bucket["crashed_badly"] += 1
            artifact["num_invalid_graphs_crashed_badly"] += 1
            if len(artifact["invalid_findings"]) < max_findings_records:
                artifact["invalid_findings"].append(
                    {
                        "seed": int(s),
                        "kind": outcome.invalid_kind,
                        "validator": outcome.validator,
                        "outcome": "crashed_badly",
                        "exception_type": outcome.exception_type,
                        "exception_message": outcome.exception_message,
                    }
                )

    cov = invalid_coverage_summary(
        [
            generate_invalid_program(int(invalid_seed) + i, kind=INVALID_KINDS[i % len(INVALID_KINDS)])
            for i in range(min(int(num_invalid), len(INVALID_KINDS)))
        ]
    )
    artifact["coverage"]["invalid_kinds_covered"] = cov["invalid_kinds_covered"]
    artifact["coverage"]["invalid_validators_covered"] = cov["invalid_validators_covered"]


def run_fuzzer(
    mode: str = "ci_seeded",
    seed: int = DEFAULT_SEED,
    num_graphs: int = DEFAULT_NUM_GRAPHS_CI,
    rtol: float = DEFAULT_RTOL,
    atol: float = DEFAULT_ATOL,
    minimize_failures: bool = True,
    repros_dir: Path = REPROS_DIR,
    write_repros: bool = False,
    measure_coverage: bool = False,
    include_invalid: bool = False,
    invalid_fraction: float = DEFAULT_INVALID_FRACTION,
    use_input_distributions: bool = True,
    include_torch_inductor: bool = False,
) -> Dict[str, Any]:
    """Drive the fuzzer; return the artifact dict.

    Always returns a fully-populated artifact (schema-locked). Errors
    are captured in the `errors` list rather than crashing the run, so
    a partial run still produces a parseable report.
    """
    artifact = _build_artifact_skeleton(
        mode=mode,
        seed=seed,
        num_graphs=num_graphs,
        include_invalid=include_invalid,
        include_torch_inductor=include_torch_inductor,
    )

    cov = None
    if measure_coverage:
        try:  # pragma: no cover - optional dep
            import coverage  # type: ignore

            cov = coverage.Coverage(source=[HOST_DIR])
            cov.start()
        except Exception as e:  # noqa: BLE001
            artifact["errors"].append(f"coverage.Coverage init failed: {e}")
            cov = None

    registered, reason = fdo.maybe_register_cuda_megakernel()
    artifact["cuda_megakernel_registered"] = bool(registered)
    artifact["cuda_megakernel_skip_reason"] = reason

    distribution_rng = random.Random(int(seed) ^ 0xD1571B)
    distributions_used: List[str] = []

    programs: List[GeneratedProgram] = []
    bug_counter = 0
    for i in range(int(num_graphs)):
        s = int(seed) + i
        try:
            program = generate_program(s)
            assert_program_legal(program)
        except Exception as e:  # noqa: BLE001
            artifact["errors"].append(f"seed={s}: generator failure: {type(e).__name__}: {e}")
            continue
        # Optionally resample inputs from an adversarial distribution. The
        # graph itself is unchanged so the metamorphic relations remain
        # semantically meaningful — we are stress-testing the *inputs*.
        if use_input_distributions:
            dist = pick_distribution(distribution_rng)
            program = apply_to_program(program, dist, seed=s)
            distributions_used.append(dist)
        else:
            distributions_used.append("random_normal")
        programs.append(program)
        artifact["num_graphs_generated"] += 1
        artifact["num_valid_graphs_generated"] += 1

        try:
            results = evaluate_all_relations(program, rtol=rtol, atol=atol)
        except Exception as e:  # noqa: BLE001
            artifact["errors"].append(
                f"seed={s}: evaluate_all_relations raised {type(e).__name__}: {e}"
            )
            continue
        artifact["num_graphs_evaluated"] += 1

        _update_relation_stats(artifact, results)
        # Every relation result — skipped or evaluated — is one "check"
        # the harness performed against this program.
        artifact["num_equivalence_checks"] += len(results)

        if include_torch_inductor:
            inductor_result = fdo.compare_torch_inductor(
                program, rtol=rtol, atol=atol
            )
            if inductor_result.skipped:
                artifact["inductor_skips"] += 1
            else:
                artifact["inductor_checks"] += 1
                artifact["num_equivalence_checks"] += 1
                if not inductor_result.match:
                    artifact["num_divergences_found"] += 1
                    artifact["num_real_miscompiles"] += 1
                    artifact["errors"].append(
                        f"seed={s}: torch_inductor vs numpy_reference mismatch "
                        f"max_abs={inductor_result.max_abs_error} "
                        f"max_rel={inductor_result.max_rel_error}"
                    )

        any_failure, failing_relations = _classify_divergence(results)
        if not any_failure:
            continue

        # We treat any non-skipped mismatch as a divergence. Tolerance
        # artifacts are conservatively counted: a failure with a small
        # max_abs_error AND a non-bit-exact verdict on a relation that
        # we expect bit-exact (`tiling_AB`) is a real miscompile; everything
        # else is conservatively classified by max_abs_error magnitude.
        artifact["num_divergences_found"] += 1
        is_real = False
        max_abs_overall = 0.0
        for r in results:
            if r.match or r.skipped:
                continue
            max_abs_overall = max(max_abs_overall, float(r.max_abs_error))
            if r.relation == "tiling_AB":
                is_real = True
            elif r.max_abs_error > max(10 * atol, 10 * rtol * 1.0):
                is_real = True

        if is_real:
            artifact["num_real_miscompiles"] += 1
        else:
            artifact["num_tolerance_artifacts"] += 1

        minimized = program
        min_stats: Optional[Dict[str, Any]] = None
        if minimize_failures:
            try:
                predicate = _failing_relation_predicate(
                    failing_relations, rtol=rtol, atol=atol
                )
                minimized, stats = minimize(program, predicate)
                min_stats = stats.to_dict()
            except Exception as e:  # noqa: BLE001
                artifact["errors"].append(
                    f"seed={s}: minimizer raised {type(e).__name__}: {e}"
                )
                minimized = program

        bug_counter += 1
        bug_id = f"bug_{bug_counter:03d}"
        repro_path: Optional[str] = None
        test_path: Optional[str] = None
        if write_repros and is_real:
            try:
                repro_path, test_path = _emit_repro_for_bug(
                    bug_id, minimized, failing_relations, repros_dir
                )
            except Exception as e:  # noqa: BLE001
                artifact["errors"].append(
                    f"seed={s}: repro emit failed: {type(e).__name__}: {e}"
                )

        artifact["bugs"].append(
            {
                "id": bug_id,
                "seed": int(s),
                "trigger": failing_relations,
                "is_real_miscompile": bool(is_real),
                "max_abs_error": float(max_abs_overall),
                "minimized_op_count": int(len(minimized.graph.ops)),
                "initial_op_count": int(len(program.graph.ops)),
                "repro_path": repro_path,
                "regression_test": test_path,
                "minimization_stats": min_stats,
                "input_distribution": program.metadata.get("input_distribution"),
                "graph_family": program.metadata.get("family"),
            }
        )

    # Invalid-graph pass (separate corpus, separate counters).
    if include_invalid:
        n_invalid = max(1, int(round(num_graphs * float(invalid_fraction))))
        invalid_seed = int(seed) + int(num_graphs) + 1
        _run_invalid_pass(artifact, invalid_seed=invalid_seed, num_invalid=n_invalid)

    coverage_data = coverage_summary(programs)
    artifact["coverage"]["ops_covered"] = coverage_data["ops_covered"]
    artifact["coverage"]["shape_buckets_covered"] = coverage_data["shape_buckets_covered"]
    artifact["coverage"]["kinds_covered"] = coverage_data["kinds_covered"]
    artifact["coverage"]["graph_families_covered"] = coverage_data["graph_families_covered"]

    dist_cov = input_distribution_coverage(distributions_used)
    artifact["coverage"]["input_distributions_covered"] = dist_cov["input_distributions_covered"]
    artifact["coverage"]["input_distribution_counts"] = dist_cov["input_distribution_counts"]

    _finalize_skip_rates(artifact)

    if cov is not None:  # pragma: no cover - optional dep
        try:
            cov.stop()
            cov.save()
            data = cov.get_data()
            measured = data.measured_files()
            covered = 0
            total = 0
            for fname in measured:
                if not fname.startswith(HOST_DIR):
                    continue
                analysis = cov.analysis2(fname)
                lines, _excluded, missing, _ = analysis[1], analysis[2], analysis[3], analysis[4]
                total += len(lines)
                covered += len(lines) - len(missing)
            if total > 0:
                artifact["coverage"]["pass_branch_coverage_pct"] = float(
                    covered / total * 100.0
                )
        except Exception as e:  # noqa: BLE001
            artifact["errors"].append(f"coverage analysis failed: {e}")

    return artifact


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["ci_seeded", "discovery"], default="ci_seeded")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--num-graphs", type=int, default=None)
    parser.add_argument("--rtol", type=float, default=DEFAULT_RTOL)
    parser.add_argument("--atol", type=float, default=DEFAULT_ATOL)
    parser.add_argument("--no-minimize", action="store_true")
    parser.add_argument("--write-repros", action="store_true")
    parser.add_argument("--measure-coverage", action="store_true")
    parser.add_argument(
        "--include-invalid",
        action="store_true",
        help="Generate an invalid-graph negative-fuzzing corpus alongside the valid corpus.",
    )
    parser.add_argument(
        "--invalid-fraction",
        type=float,
        default=DEFAULT_INVALID_FRACTION,
        help="Fraction of --num-graphs to use for the invalid corpus (default 0.20).",
    )
    parser.add_argument(
        "--no-input-distributions",
        action="store_true",
        help="Disable adversarial input distributions (use random_normal only).",
    )
    parser.add_argument(
        "--include-torch-inductor",
        action="store_true",
        help="Cross-check each valid graph against torch.compile(backend=inductor).",
    )
    parser.add_argument("--output", default=str(OUTPUT_JSON))
    args = parser.parse_args()

    n = args.num_graphs
    if n is None:
        n = (
            DEFAULT_NUM_GRAPHS_DISCOVERY
            if args.mode == "discovery"
            else DEFAULT_NUM_GRAPHS_CI
        )

    artifact = run_fuzzer(
        mode=args.mode,
        seed=int(args.seed),
        num_graphs=int(n),
        rtol=float(args.rtol),
        atol=float(args.atol),
        minimize_failures=(not args.no_minimize),
        write_repros=bool(args.write_repros),
        measure_coverage=bool(args.measure_coverage),
        include_invalid=bool(args.include_invalid),
        invalid_fraction=float(args.invalid_fraction),
        use_input_distributions=(not args.no_input_distributions),
        include_torch_inductor=bool(args.include_torch_inductor),
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8")
    print(
        f"[run_fuzzer] wrote {out_path} mode={artifact['mode']} "
        f"valid={artifact['num_valid_graphs_generated']} "
        f"invalid={artifact['num_invalid_graphs_generated']} "
        f"checks_equiv={artifact['num_equivalence_checks']} "
        f"inductor_checks={artifact.get('inductor_checks', 0)} "
        f"checks_rej={artifact['num_rejection_checks']} "
        f"divergences={artifact['num_divergences_found']} "
        f"real={artifact['num_real_miscompiles']} "
        f"tolerance={artifact['num_tolerance_artifacts']} "
        f"errors={len(artifact['errors'])}"
    )


if __name__ == "__main__":
    main()
