"""Task 4 tests: static cycle parity + data-independence prover + schema lock.

Validates ``firmware/host/latency_analysis.py`` end-to-end:

1. Static cycle counts match the ISA simulator's accounting byte-exactly
   on the blocked-FC corpus (naive + scheduled lowerings) over a wide
   shape sweep.
2. Mixed / D-type / extended-address synthetic programs round-trip
   through both the simulator and the static walker with identical
   cycle totals — proves the walker's word-advance logic stays in
   lockstep with the simulator across every opcode encoding.
3. The data-independence prover correctly identifies *every* shipping
   opcode as data-independent under the default allowlist AND
   correctly flags a deliberately-excluded opcode under a narrowed
   allowlist (the planted-defect test).
4. The static cycle count is invariant across the 5 adversarial input
   distributions used in the harness for a fixed shape (by
   construction: input data lives in BSTORE payloads, not in opcode
   bits, so the instruction count is shape-determined; this test
   keeps that invariant honest against future regressions in the
   lowering).
5. Schema lock on the committed ``bench/results/latency_determinism.json``
   artifact: required top-level keys present, ``status`` is one of
   the documented values, the static arm reports
   ``exact_match=True`` on every swept shape, ``data_dependent_ops_found``
   is empty, and the static distribution sweep has variance == 0.

Reality floors (gated whenever the artifact is present):
- ``status == "rtl_sim"`` OR ``status == "hardware"`` (no failed-mode
  artifact committed).
- ``static_arm_all_shapes_exact_match == True``.
- ``proof.data_dependent_ops_found == []``.
- ``data_independence[0].static_cycle_invariant == True`` and
  ``static_cycle_variance == 0``.
- If ``rtl_arm`` is present (``iverilog`` was available at regen time):
  ``data_independence[0].rtl_cycle_invariant == True`` and
  ``rtl_cycle_variance == 0``.

The artifact is regenerated by
``python firmware/host/run_latency_determinism.py [--skip-iverilog]``.
"""

from __future__ import annotations

import json
import os
import sys

import numpy as np
import pytest

HOST_DIR = os.path.dirname(os.path.abspath(__file__))
if HOST_DIR not in sys.path:
    sys.path.insert(0, HOST_DIR)

REPO_ROOT = os.path.dirname(os.path.dirname(HOST_DIR))
ARTIFACT_PATH = os.path.join(REPO_ROOT, "bench", "results", "latency_determinism.json")

from isa_encoder import (  # noqa: E402
    IsaConfig,
    encodeAccAdd,
    encodeBarrier,
    encodeBufferXfer,
    encodeBurstStore,
    encodeFetch,
    encodeHalt,
    encodeLoadInputs,
    encodeLoadWeights,
    encodeNop,
    encodePeSelect,
    encodeRun,
    encodeStoreValues,
)
from isa_simulator import simulate_program_bytes  # noqa: E402
from latency_analysis import (  # noqa: E402
    DEFAULT_DATA_INDEPENDENT_OPS,
    DTYPE_SUBOP_NAMES,
    OPCODE_NAMES,
    analyze_program,
    opcode_label,
    prove_data_independent,
    static_cycles_simulator,
)
from lowering_blocked_fc_utpu import lower_blocked_fc_program_utpu  # noqa: E402
from run_latency_determinism import (  # noqa: E402
    DEFAULT_DISTRIBUTIONS,
    _compile_program,
    _draw_input_vector,
)
from scheduler_allocator import lower_blocked_fc_program_scheduled  # noqa: E402


# ---------------------------------------------------------------------------
# 1. Static cycle parity vs the ISA simulator
# ---------------------------------------------------------------------------


_BLOCKED_FC_SHAPES = [
    (32, 32),
    (32, 64),
    (64, 32),
    (64, 64),
    (128, 32),
    (16, 32),
]


@pytest.mark.parametrize("m,k", _BLOCKED_FC_SHAPES)
def test_static_cycles_match_simulator_blocked_fc_naive(m, k):
    seed = 0xC0DE + m * 31 + k
    rng = np.random.default_rng(seed)
    w = rng.integers(low=-8, high=8, size=(m, k), dtype=np.int8)
    x = rng.integers(low=-8, high=8, size=k, dtype=np.int8)
    naive = lower_blocked_fc_program_utpu(
        w, x, m, k, 16, False, True, 256, 0, 320, prog_depth=1024
    )
    sim = simulate_program_bytes(naive["program"], array_size=16)
    static = static_cycles_simulator(naive["program"])
    assert static.total_cycles == sim.cycle_count_sequential, (
        f"naive shape=({m},{k}): static={static.total_cycles} "
        f"sim={sim.cycle_count_sequential}"
    )
    assert static.halted is True
    sum_per_op = sum(static.per_opcode_cycles.values())
    assert sum_per_op == static.total_cycles, (
        "per_opcode_cycles must sum to total_cycles "
        f"({sum_per_op} != {static.total_cycles})"
    )


@pytest.mark.parametrize("m,k", _BLOCKED_FC_SHAPES)
def test_static_cycles_match_simulator_blocked_fc_scheduled(m, k):
    seed = 0xC0DE + m * 31 + k
    rng = np.random.default_rng(seed)
    w = rng.integers(low=-8, high=8, size=(m, k), dtype=np.int8)
    x = rng.integers(low=-8, high=8, size=k, dtype=np.int8)
    sched = lower_blocked_fc_program_scheduled(
        w, x, m, k, 16, False, True, 256, 0, 320
    )
    sim = simulate_program_bytes(sched["program"], array_size=16)
    static = static_cycles_simulator(sched["program"])
    assert static.total_cycles == sim.cycle_count_sequential, (
        f"sched shape=({m},{k}): static={static.total_cycles} "
        f"sim={sim.cycle_count_sequential}"
    )


def test_static_cycles_match_simulator_bstore_and_nop_mixed():
    prog = bytearray()
    prog += encodeStoreValues(0, [1, 2, 3, 4])
    prog += encodeBurstStore(8, [0x1111, 0x2222, 0x3333, 0x4444, 0x5555])
    prog += encodeLoadInputs(0)
    prog += encodeLoadWeights(8)
    prog += encodeRun(
        64, compute_en=True, quantize_en=True, relu_en=False, acc_clear_en=True
    )
    prog += encodeFetch(64, top_half=False)
    prog += encodeNop()
    prog += encodeHalt()
    prog_bytes = bytes(prog)
    sim = simulate_program_bytes(prog_bytes, array_size=4)
    static = static_cycles_simulator(prog_bytes)
    assert static.total_cycles == sim.cycle_count_sequential
    assert static.per_opcode_counts.get("BSTORE") == 1
    assert static.per_opcode_counts.get("NOP") == 1
    assert static.per_opcode_counts.get("HALT") == 1
    # BSTORE cost = 2 + count = 2 + 5 = 7.
    assert static.per_opcode_cycles.get("BSTORE") == 7


def test_static_cycles_match_simulator_dtype_subops():
    prog = bytearray()
    prog += encodePeSelect(0)
    prog += encodeBurstStore(0, [0x1, 0x2, 0x3, 0x4])
    prog += encodeBufferXfer(src_pe=0, dst_pe=1, src_addr=0, dst_addr=10, count=4)
    prog += encodeBarrier(0)
    prog += encodeAccAdd(src_pe=0, dst_pe=1)
    prog += encodePeSelect(1)
    prog += encodeLoadWeights(10)
    prog += encodeHalt()
    prog_bytes = bytes(prog)
    sim = simulate_program_bytes(prog_bytes, num_pe=2, array_size=4)
    static = static_cycles_simulator(prog_bytes)
    assert static.total_cycles == sim.cycle_count_sequential
    for token in ("PE_SELECT", "BSTORE", "BUFFER_XFER", "BARRIER", "ACC_ADD", "HALT"):
        assert token in static.per_opcode_counts, (
            f"{token!r} not in {sorted(static.per_opcode_counts)}"
        )
    # BUFFER_XFER cost = 2 + count = 2 + 4 = 6.
    assert static.per_opcode_cycles.get("BUFFER_XFER") == 6


def test_static_cycles_match_simulator_extended_address_int8():
    cfg = IsaConfig(instruction_width=16, address_width=14, compute_data_width=8)
    prog = bytearray()
    prog += encodeStoreValues(100, [1, 2], cfg=cfg)
    prog += encodeBurstStore(200, [0x1111, 0x2222, 0x3333], cfg=cfg)
    prog += encodeLoadInputs(100, cfg=cfg)
    prog += encodeLoadWeights(200, cfg=cfg)
    prog += encodeRun(
        500,
        compute_en=True,
        quantize_en=True,
        relu_en=False,
        acc_clear_en=True,
        cfg=cfg,
    )
    prog += encodeFetch(500, cfg=cfg)
    prog += encodeHalt(cfg=cfg)
    prog_bytes = bytes(prog)
    sim = simulate_program_bytes(prog_bytes, cfg=cfg, array_size=4)
    static = static_cycles_simulator(prog_bytes, cfg=cfg)
    assert static.total_cycles == sim.cycle_count_sequential


# ---------------------------------------------------------------------------
# 2. Static cycle invariance under input distributions (no RTL required)
# ---------------------------------------------------------------------------


def test_static_cycles_invariant_across_all_5_input_distributions():
    M, K = 32, 32
    counts = []
    for i, dist in enumerate(DEFAULT_DISTRIBUTIONS):
        rng = np.random.default_rng(20260527 + i)
        x = _draw_input_vector(dist, K, rng)
        case = _compile_program(M, K, x_vector=x)
        static = static_cycles_simulator(case["program"])
        sim = simulate_program_bytes(case["program"], array_size=16)
        counts.append((dist, int(static.total_cycles), int(sim.cycle_count_sequential)))
    static_values = {c[1] for c in counts}
    sim_values = {c[2] for c in counts}
    assert len(static_values) == 1, (
        f"static cycle counts varied across distributions: {counts}"
    )
    assert len(sim_values) == 1, (
        f"simulator cycle counts varied across distributions: {counts}"
    )
    assert static_values == sim_values, (
        f"static disagreed with simulator: static={static_values} sim={sim_values}"
    )


def test_static_cycles_invariant_across_distributions_on_multiple_shapes():
    for M, K in [(32, 32), (32, 64), (64, 32)]:
        counts = set()
        for i, dist in enumerate(DEFAULT_DISTRIBUTIONS):
            rng = np.random.default_rng(20260527 + i)
            x = _draw_input_vector(dist, K, rng)
            case = _compile_program(M, K, x_vector=x)
            counts.add(int(static_cycles_simulator(case["program"]).total_cycles))
        assert len(counts) == 1, (
            f"shape=({M},{K}) static counts varied across distributions: {counts}"
        )


# ---------------------------------------------------------------------------
# 3. Data-independence prover (default + planted defect)
# ---------------------------------------------------------------------------


def test_prove_data_independent_clean_on_blocked_fc_naive():
    seed = 0xC0DE + 32 * 31 + 32
    rng = np.random.default_rng(seed)
    w = rng.integers(low=-8, high=8, size=(32, 32), dtype=np.int8)
    x = rng.integers(low=-8, high=8, size=32, dtype=np.int8)
    case = lower_blocked_fc_program_utpu(
        w, x, 32, 32, 16, False, True, 256, 0, 320, prog_depth=1024
    )
    proof = prove_data_independent(case["program"])
    assert proof.is_proven is True
    assert proof.data_dependent_ops_found == ()
    for token in proof.data_independent_ops_observed:
        assert token in DEFAULT_DATA_INDEPENDENT_OPS


def test_prove_data_independent_clean_on_dtype_subops_program():
    prog = bytearray()
    prog += encodePeSelect(0)
    prog += encodeBurstStore(0, [0x1, 0x2, 0x3, 0x4])
    prog += encodeBufferXfer(src_pe=0, dst_pe=1, src_addr=0, dst_addr=10, count=4)
    prog += encodeBarrier(0)
    prog += encodeAccAdd(src_pe=0, dst_pe=1)
    prog += encodePeSelect(1)
    prog += encodeLoadWeights(10)
    prog += encodeHalt()
    proof = prove_data_independent(bytes(prog))
    assert proof.is_proven is True
    assert proof.data_dependent_ops_found == ()
    for token in ("PE_SELECT", "BUFFER_XFER", "BARRIER", "ACC_ADD"):
        assert token in proof.data_independent_ops_observed


def test_planted_defect_prover_flags_excluded_opcode_run():
    """Plant a defect by narrowing the allowlist to exclude ``RUN`` and
    verify the prover correctly flags the RUN instructions present in a
    blocked-FC program. This is the proof-of-teeth gate required by
    plan section 6.5: 'data-independence prover flags a planted
    data-dependent op'.
    """
    seed = 0xC0DE + 32 * 31 + 32
    rng = np.random.default_rng(seed)
    w = rng.integers(low=-8, high=8, size=(32, 32), dtype=np.int8)
    x = rng.integers(low=-8, high=8, size=32, dtype=np.int8)
    case = lower_blocked_fc_program_utpu(
        w, x, 32, 32, 16, False, True, 256, 0, 320, prog_depth=1024
    )
    narrowed = tuple(op for op in DEFAULT_DATA_INDEPENDENT_OPS if op != "RUN")
    assert "RUN" not in narrowed
    proof = prove_data_independent(case["program"], allowed_opcodes=narrowed)
    assert proof.is_proven is False
    assert "RUN" in proof.data_dependent_ops_found, (
        f"RUN not flagged when excluded from allowlist: {proof.data_dependent_ops_found}"
    )
    assert "STORE" not in proof.data_dependent_ops_found
    assert "LOAD" not in proof.data_dependent_ops_found
    assert "HALT" not in proof.data_dependent_ops_found


def test_planted_defect_prover_flags_excluded_buffer_xfer_subop():
    prog = bytearray()
    prog += encodePeSelect(0)
    prog += encodeBufferXfer(src_pe=0, dst_pe=1, src_addr=0, dst_addr=10, count=4)
    prog += encodeBarrier(0)
    prog += encodeHalt()
    narrowed = tuple(
        op for op in DEFAULT_DATA_INDEPENDENT_OPS if op != "BUFFER_XFER"
    )
    proof = prove_data_independent(bytes(prog), allowed_opcodes=narrowed)
    assert proof.is_proven is False
    assert "BUFFER_XFER" in proof.data_dependent_ops_found
    assert "BARRIER" not in proof.data_dependent_ops_found
    assert "PE_SELECT" not in proof.data_dependent_ops_found


def test_default_allowlist_covers_every_shipping_opcode_token():
    """The default allowlist must include every opcode + D-type subop
    token currently encoded by ``isa_encoder.py``. If a future opcode
    is added without updating ``DEFAULT_DATA_INDEPENDENT_OPS``, this
    test must fail and force the prover to be re-audited.
    """
    expected_tokens = {OPCODE_NAMES[code] for code in OPCODE_NAMES if code != 0b111}
    expected_tokens.update(DTYPE_SUBOP_NAMES.values())
    allowed = set(DEFAULT_DATA_INDEPENDENT_OPS)
    missing = expected_tokens - allowed
    extra = allowed - expected_tokens
    assert not missing, f"DEFAULT_DATA_INDEPENDENT_OPS missing tokens: {missing}"
    assert not extra, f"DEFAULT_DATA_INDEPENDENT_OPS has unknown tokens: {extra}"


# ---------------------------------------------------------------------------
# 4. analyze_program bundle smoke
# ---------------------------------------------------------------------------


def test_analyze_program_bundles_static_cycles_and_proof():
    seed = 0xC0DE + 64 * 31 + 32
    rng = np.random.default_rng(seed)
    w = rng.integers(low=-8, high=8, size=(64, 32), dtype=np.int8)
    x = rng.integers(low=-8, high=8, size=32, dtype=np.int8)
    case = lower_blocked_fc_program_utpu(
        w, x, 64, 32, 16, False, True, 256, 0, 320, prog_depth=1024
    )
    bundle = analyze_program(case["program"])
    assert bundle["data_independence_proven"] is True
    assert bundle["data_dependent_ops_found"] == []
    assert bundle["static_cycles"] > 0
    assert bundle["halted"] is True
    assert sum(bundle["per_opcode_cycles"].values()) == bundle["static_cycles"]


# ---------------------------------------------------------------------------
# 5. Schema lock on the committed artifact
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def artifact():
    if not os.path.exists(ARTIFACT_PATH):
        pytest.skip(
            f"{ARTIFACT_PATH} not found; run "
            "`python firmware/host/run_latency_determinism.py [--skip-iverilog]` first."
        )
    with open(ARTIFACT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def test_artifact_required_top_level_keys(artifact):
    required = {
        "schema_version",
        "generated_at_utc",
        "status",
        "shapes",
        "static_vs_sim",
        "static_arm_all_shapes_exact_match",
        "data_independence",
        "proof",
        "on_silicon",
        "scope_note",
        "methodology",
        "rtl_arm",
        "iverilog_version",
        "host",
        "distribution_sweep_detail",
    }
    missing = required - set(artifact.keys())
    assert not missing, f"missing top-level keys: {missing}"
    assert artifact["schema_version"] == 1


def test_artifact_status_value(artifact):
    assert artifact["status"] in {"rtl_sim", "hardware"}


def test_artifact_static_arm_all_shapes_exact_match(artifact):
    assert artifact["static_arm_all_shapes_exact_match"] is True
    for entry in artifact["static_vs_sim"]:
        assert entry["exact_match"] is True, (
            f"shape {entry['shape']}: static={entry['static_cycles']} "
            f"sim={entry['simulator_cycles']}"
        )
        assert entry["data_independence_proven"] is True
        assert entry["data_dependent_ops_found"] == []


def test_artifact_proof_data_dependent_ops_empty(artifact):
    proof = artifact["proof"]
    assert proof["data_dependent_ops_found"] == []
    assert set(proof["data_independent_ops"]) == set(DEFAULT_DATA_INDEPENDENT_OPS)
    union_observed = set(proof["data_independent_ops_observed_union"])
    assert union_observed.issubset(set(proof["data_independent_ops"]))
    assert "STORE" in union_observed
    assert "LOAD" in union_observed
    assert "RUN" in union_observed
    assert "FETCH" in union_observed
    assert "HALT" in union_observed


def test_artifact_data_independence_static_invariant(artifact):
    blocks = artifact["data_independence"]
    assert len(blocks) >= 1
    block = blocks[0]
    assert block["static_cycle_invariant"] is True
    assert int(block["static_cycle_variance"]) == 0
    assert block["simulator_cycle_invariant"] is True
    assert int(block["simulator_cycle_variance"]) == 0
    assert len(block["distributions_tested"]) >= 5


def test_artifact_rtl_arm_if_present_reports_zero_variance(artifact):
    block = artifact["data_independence"][0]
    if not block.get("rtl_arm_present"):
        pytest.skip(
            "rtl_arm not present (iverilog stub mode); static-arm gates only."
        )
    assert block["rtl_cycle_invariant"] is True, (
        "rtl_cycle_invariant=False with iverilog arm present is a "
        "Task 4 acceptance-criterion violation"
    )
    assert int(block["rtl_cycle_variance"]) == 0


def test_artifact_on_silicon_status_documented(artifact):
    onsi = artifact["on_silicon"]
    assert onsi["status"] in {
        "rtl_sim",
        "rtl_sim_unavailable_no_iverilog",
        "rtl_sim_skipped_by_user",
        "hardware",
    }
    if onsi["status"] != "hardware":
        assert onsi["onchip_counter_cycles"] is None
        assert onsi["matches_static"] is None


def test_artifact_scope_note_present_and_documents_simulator_match(artifact):
    note = artifact["scope_note"]
    assert isinstance(note, str) and len(note) > 50
    # The honest scope must mention that the static match is against
    # the simulator (NOT absolute RTL counts).
    lower = note.lower()
    assert "simulator" in lower
    assert "p4.1" in lower or "rtl-corroborated" in lower or "percentage" in lower
    assert "data-independ" in lower or "constant-time" in lower


def test_artifact_distribution_sweep_detail_matches_data_independence_block(artifact):
    sweep = artifact["distribution_sweep_detail"]
    block = artifact["data_independence"][0]
    assert sweep["shape"] == block["shape"]
    assert sweep["distributions"] == block["distributions_tested"]
    assert int(sweep["static_cycle_variance"]) == int(block["static_cycle_variance"])
    for d in sweep["per_distribution"]:
        assert d["static_equals_simulator"] is True


# ---------------------------------------------------------------------------
# 6. Misc API surface stability
# ---------------------------------------------------------------------------


def test_opcode_label_handles_dtype_subops():
    from isa_encoder import OPCODE_DTYPE, DTYPE_SUBOP_BUFFER_XFER

    assert opcode_label(OPCODE_DTYPE, DTYPE_SUBOP_BUFFER_XFER) == "BUFFER_XFER"
    assert opcode_label(OPCODE_DTYPE) == "DTYPE"


def test_static_cycle_result_fields_present():
    prog = bytearray()
    prog += encodeStoreValues(0, [1, 2, 3, 4])
    prog += encodeHalt()
    static = static_cycles_simulator(bytes(prog))
    assert static.total_cycles > 0
    assert static.instructions_decoded == 2  # STORE + HALT
    assert static.halted is True
    assert "STORE" in static.per_opcode_counts
    assert "HALT" in static.per_opcode_counts
